### ISSUE TITLE
custom colour issue

### ISSUE THREAD

**Issue by Yseii** [damon-murdoch/wmmt-car-editor#2]
apparently I had selected a custom colour and save on my data but it seems to not work as i select any stock colour it chooses to be the stock colour instead of the selected custom colour. is there any solution to solve this issue? thank you very much for responding

**Comment by damon-murdoch** [comment]
Hi - I don't maintain this program anymore :) Please try it out using the wmmt file editor - https://www.dragapult.xyz/wmmt-file-editor cheers :)
