### ISSUE TITLE
No matter what color I put, it always comes out as silver.

### ISSUE THREAD

**Issue by spukiky** [damon-murdoch/wmmt-car-editor#3]
![image](https://user-images.githubusercontent.com/114479916/192491483-aabebe98-b968-47db-b1c0-6c5f88e71d7c.png)
![image](https://user-images.githubusercontent.com/114479916/192491535-0f40dc26-8b88-4cd3-9c5e-16bc74ebe4f0.png)

I use the SVX and no matter what color I put it always results to Silver car. Whether I put Not available on stock color or not, whether I put 1 or 20 as the custom color, it's always Silver.

**Comment by damon-murdoch** [comment]
If you are using the official Teknoparrot build of Maximum tune 6 (Not my branch of OpenParrot), it doesn't read the custom colour value sadly :( So it won't work unless you play MT5/5DX+ or try using the OpenParrot release on my Github.
